name: 3d_moments
channels:
  - pytorch3d
  - pytorch
  - iopath
  - fvcore
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - fvcore=0.1.5.post20210915=py37
  - intel-openmp=2021.3.0=h06a4308_3350
  - iopath=0.1.9=py37
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - olefile=0.46=py37_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.3.1=py37h2c7a002_0
  - portalocker=2.3.2=py37h89c1867_0
  - python=3.7.11=h12debd9_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.7.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytorch3d=0.6.0=py37_cu101_pyt171
  - pyyaml=5.4.1=py37h5e8e339_0
  - readline=8.1=h27cfd23_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.7.2=py37
  - torchvision=0.8.2=py37_cu101
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.15.0
    - beautifulsoup4==4.10.0
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - configargparse==1.5.3
    - cupy-cuda101==9.6.0
    - cycler==0.10.0
    - dill==0.3.4
    - fastrlock==0.8
    - filelock==3.3.0
    - gdown==4.4.0
    - google-auth==2.3.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.41.0
    - h5py==3.5.0
    - idna==3.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.8.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - kornia==0.5.11
    - lpips==0.1.4
    - markdown==3.3.4
    - matplotlib==3.4.3
    - networkx==2.6.3
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - packaging==21.0
    - pandas==1.3.4
    - pip==22.1.2
    - plotly==5.3.1
    - protobuf==3.18.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pyquaternion==0.9.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.18.3
    - scikit-learn==1.0
    - scipy==1.7.1
    - setuptools==62.4.0
    - sklearn==0.0
    - soupsieve==2.2.1
    - tenacity==8.0.1
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - threadpoolctl==3.0.0
    - tifffile==2021.10.12
    - timm==0.4.5
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - zipp==3.6.0
prefix: /phoenix/S7/qw246/anaconda3/envs/3d_moments
